# File Path: /docker/docker-compose.yml

version: "3.8"

services:
  vscode_dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.vscode
    volumes:
      - ../workspace:/workspace
    ports:
      - "8080:8080"
    container_name: vscode_dev
    command: ["sleep", "infinity"]

  api_gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gateway
    ports:
      - "8000:8000"
    depends_on:
      - vscode_dev
    environment:
      - ENV=production
    volumes:
      - ../api_gateway:/app
    container_name: api_gateway
